name: dart_io
version: 0.0.2+try-two
author: Thomas Caserta <tom@caserta.co.uk>
description: Java-like io library
homepage: https://github.com/TomCaserta/dart_io
dependencies:
  archive: any
  fixnum: any
